server:
  port: 80

# 콘솔 ANSI 색상
spring:
  output:
    ansi:
      enabled: always

# ThymeLeaf 설정
  thymeleaf:
    cache : false
    prefix : classpath:templates/views/

# datasource 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostname}:${rds.host}/${rds.db.name}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${rds.username}
    password: ${rds.password}

  #security
  security:
    user:
      name: user1 # default security username
      password: 1234 # password

    # oauth2 client
    oauth2:
      client:
        registration:
          google:
            client-id: 678852163160-c30ph75ptcaocpnt0sjujc63ide9kn6q.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 841633284412597 #앱 ID
            client-secret: a463f62827f1636b8ef16e55f4e932e2 #앱 시크릿 코드
            scope:
              - email
              - public_profile
          naver:
            client-id: bKiPm4nijyqCiM93pfic
            client-secret: TDwu08bytt
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        #provider 제공
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

# MyBatis 매퍼(mapper) 파일 위치 설정
# src/main/resources 이하의 경로 지정

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

app:
  #파일 업로드 경로
  upload:
    path: upload

  # 페이징 관련 세팅값
  pagination:
    write_pages: 10  # 기본 write_pages 값. 한 [페이징] 당 몇개의 페이지가 표시되나
    page_rows: 10    # 기본 page_rows 값.  한 '페이지'에 몇개의 글을 리스트 할것인가?

# OAuth2
  oauth2:

    password: 1234
    # kakao 로그인 관련 세팅값
    kakao:
      client-id: 9da2eca47bbe217c70ba9dd8ad87e47a  #앱 키
      redirect-uri: http://localhost:8080/oauth2/kakao/callback # redirect uri
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me









